BEGIN
   SAL_DW_CL_USER.pkg_cleansing_dw_star.games;
   SAL_DW_CL_USER.pkg_cleansing_dw_star.customers;
   SAL_DW_CL_USER.pkg_cleansing_dw_star.companies;
   SAL_DW_CL_USER.pkg_cleansing_dw_star.geo_locations;
   SAL_DW_CL_USER.pkg_cleansing_dw_star.sales;
   SAL_DW_CL_USER.pkg_cleansing_dw_star.ld_date;
   SAL_DW_CL_USER.pkg_cleansing_dw_star.gen_periods;
END;
